### ISSUE TITLE
DEPRECATION warning 

### ISSUE THREAD

**Issue by cwiese** [Addepar/ember-table-addon#9]
Are we still expecting these DEPRECATION (1000's of them for each row/cell) ?....I just added Financial Tree table example to Ember 1.11 project.

DEPRECATION: You're attempting to render a view by passing contentBinding to a view helper, but this syntax is deprecated. You should use `content=someValue` instead.
        at mergeGenericViewBindings (http://localhost:4200/p3/assets/vendor.js:17115:28)
        at Object.mergeViewBindings [as default] (http://localhost:4200/p3/assets/vendor.js:17094:5)
        at viewHelper (http://localhost:4200/p3/assets/vendor.js:16477:33)
        at inline (http://localhost:4200/p3/assets/vendor.js:16762:40)
        at Object.render (http://localhost:4200/p3/assets/p3-next.js:14008:9)
        at renderHTMLBarsTemplate (http://localhost:4200/p3/assets/vendor.js:17253:21)
        at renderView (http://localhost:4200/p3/assets/vendor.js:17220:16)
        at renderView (http://localhost:4200/p3/assets/vendor.js:46166:5)
        at mixin.Mixin.create.render (http://localhost:4200/p3/assets/vendor.js:46187:7)

**Comment by azirbel** [comment]
Yep, I'm still expecting some of that. If you search the code base, there is still some instance of `xBinding` in handlebars templates (which should just be `x=...`). We also use view helpers in some old-fashioned ways.

I don't plan to address this very soon - tests, API changes (https://github.com/Addepar/ember-table/issues/296), and 1.0.0 release are first on my list. But if you (or anyone else) can dig into this and make a pull request, we'd really appreciate it and would be happy to merge it in.

**Comment by jrhe** [comment]
I have a commit which sorts this and another which sorts the styleBinding warnings. Not sure how I can isolate those commits to do a PR though as they are munged together. Also have single selection keyboard nav to do a PR for. Any guidance appreciated.

**Comment by azirbel** [comment]
@jrhe have you seen https://github.com/Addepar/ember-table-addon/pull/15?

Those both sound like great improvements - I'd love to see your work! In the worst case, you can just make a big PR and at least we can see your ideas. I can't guarantee it'll be merged in that state, but then we can break it down together.

**Comment by jrhe** [comment]
Yup saw this. Does the same thing and the code is pretty much identical to what I did just after I commented :p. The selection code probably needs a code review. I will do a mega PR and you can see what you think.

**Comment by azirbel** [comment]
Closing this to encourage discussion to move back to https://github.com/Addepar/ember-table. Some attempts have been made to fix this in PRs already.
